FROM mhart/alpine-node
WORKDIR /dist
COPY package*.json ./

COPY . /dist
COPY ./entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ADD package.json yarn.lock /dist/

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1


RUN \
  apk update                     && \
  apk add bash                   && \
  apk add --no-cache python3 python3-dev && \ 
  npm install -G yarn gatsby gatsby-cli ts-node typescript && \
  npm install
EXPOSE 8000
ENTRYPOINT ["/entrypoint.sh"]
